---
packages:
  chip: !include ../bk72xx.yaml
  comm: !include ../common.yaml
  togl: !include ../restart_switch.yaml

substitutions:
  board: generic-bk7231t-qfn32-tuya
  project_name: untergeek.beken_sw02-03
  project_version: 1.0.0
  id1: relay1
  id2: relay2
  id3: relay3
  name1: "Top Switch"
  icon1: mdi:toggle-switch-variant
  name2: "Middle Switch"
  icon2: mdi:toggle-switch-variant
  name3: "Bottom Switch"
  icon3: mdi:toggle-switch-variant

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

# status_led:
#   pin:
#     number: P0
#     inverted: true
    # inverted: True will yield a RED WiFi status light instead of BLUE
    # P23 is the LED RED Status. "inverted: false" means it's off by default

output:
  - platform: gpio
    id: output_led_1
    pin: P1
  - platform: gpio
    id: output_led_2
    pin: P26
  - platform: gpio
    id: output_led_3
    pin: P14
  # Testing other pins
  - platform: gpio
    id: led0
    pin: P0
  - platform: gpio
    id: led11
    pin: P11
  - platform: gpio
    id: led23
    pin: P23
# In use:
#  0
#  1
#  6
#  7
#  8
#  9
#  10
#  11
#  14
#  23
#  24
#  26

#  Not in use (probably not even soldered)
#  P20
#  P21
#  P22

light:
  - platform: binary
    id: status1
    internal: true
    output: output_led_1
  - platform: binary
    id: status2
    internal: true
    output: output_led_2
  - platform: binary
    id: status3
    internal: true
    output: output_led_3
  # Testing other LEDs
  - platform: binary
    id: test0
    output: led0
  - platform: binary
    id: test11
    output: led11
  - platform: binary
    id: test23
    output: led23

switch:
  - platform: gpio
    id: ${id1}
    pin: P6
    name: ${name1}
    icon: ${icon1}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: status1
    on_turn_off:
      - light.turn_off: status1
  - platform: gpio
    id: ${id2}
    pin: P7
    name: ${name2}
    icon: ${icon2}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: status2
    on_turn_off:
      - light.turn_off: status2
  - platform: gpio
    id: ${id3}
    pin: P9
    name: ${name3}
    icon: ${icon3}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: status3
    on_turn_off:
      - light.turn_off: status3
  - platform: template
    id: s0
    name: P0
    on_turn_on:
      - light.turn_on: test0
    on_turn_off:
      - light.turn_off: test0
  - platform: template
    id: s11
    name: P11
    on_turn_on:
      - light.turn_on: test11
    on_turn_off:
      - light.turn_off: test11
  - platform: template
    id: s23
    name: P23
    on_turn_on:
      - light.turn_on: test23
    on_turn_off:
      - light.turn_off: test23

binary_sensor:
  - platform: gpio
    internal: true
    name: "${friendly_name} Button 1"
    pin:
      number: P24
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: ${id1}
  - platform: gpio
    internal: true
    name: "${friendly_name} Button 2"
    pin:
      number: P8
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: ${id2}
  - platform: gpio
    internal: true
    name: "${friendly_name} Button 3"
    pin:
      number: P10
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: ${id3}
