---
packages:
  main: !include
    file: ../esphome.yaml
    vars:
      project_name: untergeek.bpa800-rgb2-ag-2
      project_version: 1.2.0
  chip: !include
    file: ../esp8266.yaml
    vars:
      board: esp01_1m
  sync: !include ../time.yaml
  togl: !include ../restart_switch.yaml
  logs: !include ../logging.yaml

substitutions:
  cold: 6500 K
  warm: 2700 K
  gamma: 0.0
  restore_mode: RESTORE_DEFAULT_OFF

### Change from defaults in substitutions

# If any value needs changing, use top-level substitutions in your main config, or package import

#packages:
#  remote: !include
#    file: template/bpa800-rgb2-ag-2.yaml
#    vars:
#      cold: # custom temp
#      warm: # custom temp
#      gamma: # custom gamma correction
#      restore_mode: # custom restore_mode value

# Feit BPA800/RGBW/AG/2
# NOT the BPA800/RGBW/AG/2(P)
sm16716:
  data_pin: GPIO14
  clock_pin: GPIO4
  num_channels: 3
  num_chips: 1

output:
  - platform: sm16716
    id: output_red
    channel: 0
    power_supply: rgb_power
  - platform: sm16716
    id: output_green
    channel: 1
    power_supply: rgb_power
  - platform: sm16716
    id: output_blue
    channel: 2
    power_supply: rgb_power
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO05

light:
  - platform: rgbww
    name: "${friendly_name}"
    color_interlock: true
    restore_mode: ${restore_mode}
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: ${cold}
    warm_white_color_temperature: ${warm}
    gamma_correct: ${gamma}

power_supply:
  - id: rgb_power
    pin: GPIO13

