---
# We track the project name and version here in the template
packages:
  main: !include
    file: ../esphome.yaml
    vars:
      project_name: untergeek.bpdim
      project_version: 1.2.2
  chip: !include
    file: ../esp8266.yaml
    vars:
      board: esp01_1m
  sync: !include ../time.yaml
  togl: !include ../restart_switch.yaml
  logs: !include ../logging.yaml
  uptm: !include ../uptime.yaml
  vers: !include ../version.yaml
  wifi: !include ../wifi_signal.yaml
  

substitutions:
  light_id: dimmer
  icon: "mdi:light-switch"
  min: "10"
  max: "1000"
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud: "9600"

### Change from default values in substitutions

# If any value needs changing, set substitutions in the main configuration file, or use vars during package import

#packages:
#  remote: !include
#    file: template/bpdim.yaml
#    vars:
#      id: # custom id
#      icon: # custom icon
#      min: # custom minimum brightness (floor is 0)
#      max: # custom maximum brightness (ceiling is 1000)
#      rx_pin: # custom GPIO
#      tx_pin: # custom GPIO
#      baud: # custom serial baud rate

uart:
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: ${baud}

tuya:

light:
  - platform: "tuya"
    id: ${light_id}
    icon: ${icon}
    name: "${friendly_name}"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: ${min}
    max_value: ${max}

