---
packages:
  chip: !include ../esp8266.yaml
  comm: !include ../common.yaml
  togl: !include ../restart_switch.yaml
  tmpl: !include
    file: ks602.yaml
    vars:
      icon: "mdi:light-switch"
      led_id: led1
      led_pin: GPIO16
      relay_id: relay1
      relay_pin: GPIO14
      button_pin: GPIO0

substitutions:
  board: esp01_1m
  project_name: untergeek.gosund-ks602
  project_version: 1.0.1

# The status_led is part of the gosund-ks602s, but not the generic ks602 parent

status_led:
  pin:
    number: GPIO2
    inverted: True
