---
### For ESP8266 based blasters -- including ESP12-E analogs like the Tuya CB3S --
### the GPIOs all seem to be the same

# ESP8266
substitutions:
  button_pin: GPIO13
  ir_rx_pin: GPIO5
  wifi_led_pin: GPIO4
  ir_tx_pin: GPIO14
  duty_pct: 50%

# CB3S Substitutions:
# substitutions:
#   button_pin: P6
#   ir_rx_pin: P7
#   wifi_led_pin: P8
#   ir_tx_pin: P26
#   duty_pct: 50%

remote_receiver:
  id: ir_rx
  pin:
    number: ${ir_rx_pin}
    inverted: ${inverted}

### Change from default values in substitutions

# If any value needs changing, use substitutions in the main configuration file, or use package import

#packages:
#  remote: !include
#    file: template/ir_rx.yaml
#    vars:
#      ir_rx_pin: # different GPIO
#      inverted: # differnt value

# If you really need to mess with it, use the !extend functionality:

# remote_receiver:
#   - id: !extend ir_rx
#     pin:
#       number: # Other GPIO
#       inverted: # True or False
#     dump: # all, or a list of individual codes 

# See https://esphome.io/components/remote_receiver.html?highlight=remote_receiver#configuration-variables

