---
# Special odditiy that runs a weird, single-core ESP32 chip but still has BLE
substitutions:
  project_name: "untergeek.linkind_switch"
  project_version: "1.0.1"

<<: !include ../common.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10" 

switch:
  - platform: gpio
    name: Switch
    id: relay
    pin: GPIO5
    inverted: false
    on_turn_on: 
      - output.turn_on:
          id: red_led
    on_turn_off:
      - output.turn_off: 
          id: red_led

light:    
  - platform: binary
    id: greenlight
    internal: true
    name: Green LED
    output: green_led
  - platform: binary
    id: redlight
    internal: true
    name: Red LED
    output: red_led
    
output:
  - platform: gpio
    pin: GPIO14
    inverted: false
    id: green_led
  - platform: gpio
    pin: GPIO26
    inverted: false
    id: red_led


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode: INPUT_PULLUP
    name: ON Button
    internal: false
    on_click:
      - switch.turn_on: relay
           
  - platform: gpio
    pin:
      number: GPIO33
      inverted: true
      mode: INPUT_PULLUP
    name: OFF Button
    internal: False
    on_click:
      - switch.turn_off: relay

esp32_ble_tracker:
  scan_parameters:
# Adjust timing if the defaults do not work in your environment
#    interval: 1100ms
#    window: 1100ms
    continuous: false

api:
  on_client_connected:
    - esp32_ble_tracker.start_scan:
       continuous: true
  on_client_disconnected:
    - esp32_ble_tracker.stop_scan:

bluetooth_proxy:
  active: true
