---
packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files:
      - base.yaml
    refresh: 1s
  chip: !include ../esp8266.yaml
  comm: !include ../common.yaml
  togl: !include ../restart_switch.yaml

substitutions:
  board: d1_mini
  project_name: ratgdo.esphome
  project_version: "2.5"
  id_prefix: rgdo
  restore: "True"
  log_baud: "115200"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini.yaml@main

improv_serial:
