---
packages:
  chip: !include ../esp8266.yaml
  comm: !include ../common.yaml
  togl: !include ../restart_switch.yaml

substitutions:
  board: esp01_1m
  icon: "phu:smart-switch"
  project_name: untergeek.sonoff-basic
  project_version: 1.0.0

switch:
  - platform: gpio
    id: relay1
    icon: ${icon}
    name: "${friendly_name}"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay1

status_led:
  pin:
    number: GPIO13
    inverted: yes