---
packages:
  chip: !include ../esp8266.yaml
  comm: !include ../common.yaml
  togl: !include ../restart_switch.yaml

substitutions:
  board: esp01_1m
  project_name: untergeek.sonoff-s20
  project_version: 1.0.1
  device_id: relay
  icon: mdi:power-socket-us
  restore_mode: DISABLED

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - switch.toggle: ${device_id}
  - platform: status
    name: Status

switch:
  - platform: gpio
    name: Switch
    pin: GPIO12
    id: ${device_id}
    restore_mode: ${restore_mode}

status_led:
  pin:
    number: GPIO13
    inverted: true
