---
esphome:
  name: ${hostname}
  friendly_name: "${friendly_name}"
  comment: "${comment}"
  area: ${area}
  name_add_mac_suffix: false
  project:
    name: ${project_name}
    version: ${project_version}

