---
substitutions:
  button_icon: "mdi:emoticon-outline"
  datafile: "/path/to/datafile.yaml"
  
button:
  - platform: ...
    name: "${button_name} Button"
    id: "${button_name}_id"
    icon: ${button_icon}
    on_press:
      - <<: !include
          file: pronto_tx.yaml
          vars:
            <<: !include ${datafile}

