---
substitutions:
  button_icon: "mdi:emoticon-outline"
  
button:
  - platform: ...
    name: "${button_name} Button"
    id: "${button_name}_id"
    icon: ${button_icon}
    on_press:
      - <<: !include {file: "${actionfile}"}

