---
substitutions:
  button_icon: "mdi:emoticon-outline"
  times: "2"
  wait: "0ms"
  
button:
  - platform: template
    name: "${button_name} Button"
    icon: ${button_icon}
    on_press:
      remote_transmitter.transmit_pronto:
        data: ${data}
        repeat:
          times: ${times}
          wait_time: ${wait}

