---
# Older-style Candles (no dancing wick) IR Control

substitutions:
  candle_name: Older Candles
  candle_pfx: older

switch:
  - platform: template
    name: "Older Candles"
    id: ${candle_pfx}_candles
    optimistic: True
    # pronto/older_candles files already have 15 code repeats built-in
    turn_on_action:
      - remote_transmitter.transmit_pronto:
          <<: !include pronto/older_candles/on.yaml
    turn_off_action:
      - remote_transmitter.transmit_pronto:
          <<: !include pronto/older_candles/off.yaml

script:
  - id: ${candle_pfx}_off_script
    then:
      - remote_transmitter.transmit_pronto:
            <<: !include pronto/older_candles/off.yaml
      - switch.template.publish: # Also turn OFF the associated switch
        id: ${candle_pfx}_candles
        state: OFF
  - id: ${candle_pfx}_on_script
    then:
      - remote_transmitter.transmit_pronto:
            <<: !include pronto/older_candles/on.yaml
      - switch.template.publish: # Also turn OFF the associated switch
        id: ${candle_pfx}_candles
        state: ON

button:
  - platform: template
    name: Forcibly Send OFF
    id: ${candle_pfx}_off_button
    on_press:
      then:
        - script.execute:
            id: ${candle_pfx}_off_script
  - platform: template
    name: Forcibly Send ON
    id: ${candle_pfx}_on_button
    on_press:
      then:
        - script.execute:
            id: ${candle_pfx}_on_script