---
substitutions:
  button_icon: "mdi:emoticon-outline"
  reps: "1"
  wait: "15ms"
  freq: 38kHz
  
button:
  - platform: template
    name: "${button_name} Button"
    icon: ${button_icon}
    on_press:
      remote_transmitter.transmit_raw:
        carrier_frequency: ${freq}
        code: ${code}
        repeat:
          times: ${reps}
          wait_time: ${wait}

